### ISSUE TITLE
Can not connect Redis(4.0.11) docker(on centos7, network=host) cluster(3M&3S) by Jedis(2.9.0)

### ISSUE THREAD

**Issue by makebote** [xetorthio/jedis#1904]
### Expected behavior
we have another  redis(4.0.2) cluster(not in docker), working fine with Jedis2.9.0, and server conf nearly are same, is it due to docker?

### Actual behavior

Write here what happens instead ...
It always report can not get resource from pool, even though I can connect the cluster with:
"redis-cli -c -h 10.1.50.11 -p 7001" or "redis-cli -c -h public ip -p 7001"

### Redis / Jedis Configuration
here is the redis server conf file

port 7001
daemonize no
logfile "/var/log/redis/redis-server.log"
pidfile /var/run/redis.pid
cluster-require-full-coverage no
maxmemory 11453246122
protected-mode no
no-appendfsync-on-rewrite yes
cluster-enabled yes
cluster-config-file redis.conf
cluster-node-timeout 10100
appendonly yes

here is the Jedis code

import org.apache.commons.pool2.impl.GenericObjectPoolConfig;
import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.*;
public class Main {
 Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();

    jedisClusterNode.add(new HostAndPort("10.1.50.1",7001));

    jedisClusterNode.add(new HostAndPort("10.1.50.1",7002));

    jedisClusterNode.add(new HostAndPort("10.1.50.2",7001));

    jedisClusterNode.add(new HostAndPort("10.1.50.2",7002));

    jedisClusterNode.add(new HostAndPort("10.1.50.3",7001));

    jedisClusterNode.add(new HostAndPort("10.1.50.3",7002));

    JedisCluster jc = new JedisCluster(jedisClusterNode, 2000, 2000, 6, "123456", new GenericObjectPoolConfig());

    jc.set("game","diablo");

    String value = jc.get("game");

    System.out.println(value);
}
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}

#### Jedis version:
2.9.0
#### Redis version:
4.0.11
#### Java version:
1.8

**Comment by makebote** [comment]
and I also tried Jedis2.7.2 and 3.0.0m1, all of them can not work.
Jedis2.7.2 report can not parse string 7001@17001
Jedis3.0 report Caused by: redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by ThietPhamDinh** [comment]
HI everyone, I have similar issue.
I clone docker from https://github.com/Grokzen/docker-redis-cluster. and build it on local machine.
when i use redis-cli connect to cluster , everything passed. but when i connect cluster via Jedis Cluster it throw `redis.clients.jedis.exceptions.JedisClusterMaxAttemptsException: No more cluster attempts left.
` . and i don't know how to fix this issue? I'd appreciated your helping.

**Comment by anupcoded** [comment]
@ThietPhamDinh 
Where you able to solve the issue? I have a similar problem and since the thread closed before anyone could replay to you.

**Comment by zhangddjs** [comment]
I have similar issue, too. Can anyone help?

**Jedis version:**
3.0.0

**Redis version:**
5.0

**Java version:**
1.8

**redis.conf:**
port 6379
cluster-enabled  yes
cluster-config-file nodes-6379.conf
appendonly yes
appendfilename "appendonly.aof"
dir /redis


**docker-compose.yml:**
``` yml
version: "3.5"
services:
  redis-master1: 
     image: redis:5.0
     container_name: redis-master1
     working_dir: /redis
     environment:
       - PORT=6379
     ports:
       - "36391:6379"
       - "46391:16379"
     stdin_open: true
     networks:
        redis-cluster:
            ipv4_address: 172.50.0.2
     tty: true
     privileged: true
     volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master1:/redis"]
     entrypoint:
       - /bin/bash
       - redis.sh
  redis-master2:
       image: redis:5.0
       working_dir: /redis
       container_name: redis-master2
       environment:
              - PORT=6379
       networks:
          redis-cluster:
             ipv4_address: 172.50.0.3
       ports:
         - "36392:6379"
         - "46392:16379"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master2:/redis"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-master3:
       image: redis:5.0
       container_name: redis-master3
       working_dir: /redis
       environment:
              - PORT=6379
       networks:
          redis-cluster:
            ipv4_address: 172.50.0.4
       ports:
         - "36393:6379"
         - "46393:16379"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-master3:/redis"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave1:
       image: redis:5.0
       container_name: redis-slave1
       working_dir: /redis
       environment:
            - PORT=6379
       networks:
          redis-cluster:
             ipv4_address: 172.50.0.5
       ports:
         - "36394:6379"
         - "46394:16379"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave1:/redis"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave2:
       image: redis:5.0
       working_dir: /redis
       container_name: redis-slave2
       environment:
             - PORT=6379
       ports:
         - "36395:6379"
         - "46395:16379"
       stdin_open: true
       networks:
          redis-cluster:
              ipv4_address: 172.50.0.6
       tty: true
       privileged: true
       volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave2:/redis"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave3:
       image: redis:5.0
       container_name: redis-slave3
       working_dir: /redis
       environment:
          - PORT=6379
       ports:
         - "36396:6379"
         - "46396:16379"
       stdin_open: true
       networks:
          redis-cluster:
            ipv4_address: 172.50.0.7
       tty: true
       privileged: true
       volumes: ["/sdddata/covfefe/dockerdata/redis-cluster/redis-slave3:/redis"]
       entrypoint:
         - /bin/bash
         - redis.sh
networks:
  redis-cluster:
     driver: bridge
     ipam:
       driver: default
       config:
          -
           subnet: 172.50.0.0/16
```
