### ISSUE TITLE
Connect to docker redis cluster Failure

### ISSUE THREAD

**Issue by zhangddjs** [xetorthio/jedis#2209]
### Expected behavior

after I built redis cluster by docker, I wrote a unit test as follows:

``` java
clusterNodes.add(new HostAndPort("10.100.13.173", 36379));
clusterNodes.add(new HostAndPort("10.100.13.173", 36380));
clusterNodes.add(new HostAndPort("10.100.13.173", 36381));
clusterNodes.add(new HostAndPort("10.100.13.173", 36382));
clusterNodes.add(new HostAndPort("10.100.13.173", 36383));
clusterNodes.add(new HostAndPort("10.100.13.173", 36384));
jedisClients = new JedisCluster(clusterNodes);
jedisClients.set("hello", "100");
```

10.100.13.173 is the ip of the remote host machine of the redis cluster.

### Actual behavior

**Thrown Exception: No more cluster attempts left.**

### root cause:

_redis.clients.jedis.JedisClusterInfoCache.java:105 ==> this.setupNodeIfNotExist(targetNode);_

I found that the **targetNode** is **172.19.0.1:36381**

The ip **172.19.0.1** is transfered to redis container's ip here, obviously, **Unreachable**.

How can I deal with this issue?

### Steps to reproduce:

1.prepare docker-compose.yml ,redis.conf ,redis.sh
2.docker-compose up -d
3.docker run --rm -it inem0o/redis-trib create --replicas 1 10.100.13.173:363{79..84}

### docker-compose.yml

``` yml
version: "3"
services:
  redis-master1: 
    image: redis:5.0
    container_name: redis-master1
    working_dir: /redis
    ports:
      - "36379:36379"
      - "46379:46379"
    restart: always
    volumes: ["/redis-cluster/redis-master1:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-master2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-master2
    ports:
      - "36380:36380"
      - "46380:46380"
    restart: always
    volumes: ["/redis-cluster/redis-master2:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-master3:
    image: redis:5.0
    container_name: redis-master3
    working_dir: /redis
    ports:
      - "36381:36381"
      - "46381:46381"
    restart: always
    volumes: ["/redis-cluster/redis-master3:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave1:
    image: redis:5.0
    network_mode: host
    container_name: redis-slave1
    working_dir: /redis
    ports:
      - "36382:36382"
      - "46382:46382"
    restart: always
    volumes: ["/redis-cluster/redis-slave1:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave2:
    image: redis:5.0
    working_dir: /redis
    container_name: redis-slave2
    ports:
      - "36383:36383"
      - "46383:46383"
    restart: always
    volumes: ["/redis-cluster/redis-slave2:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave3:
    image: redis:5.0
    container_name: redis-slave3
    working_dir: /redis
    ports:
      - "36384:36384"
      - "46384:46384"
    restart: always
    volumes: ["/redis-cluster/redis-slave3:/redis"]
    entrypoint:
      - /bin/bash
      - redis.sh
```

### redis.conf

```
port 36379
cluster-enabled  yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```

### redis.sh

``` bash
redis-server /redis/redis.conf
```

#### Jedis version:

v3.3.0

#### Redis version:

v5.0.9

#### Java version:

v1.8
